// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/zerotwo-dash/HUD.tsx": () => import("../components/mockups/zerotwo-dash/HUD.tsx"),
  "./components/mockups/zerotwo-dash/Phantom.tsx": () => import("../components/mockups/zerotwo-dash/Phantom.tsx"),
  "./components/mockups/zerotwo-dash/Sakura.tsx": () => import("../components/mockups/zerotwo-dash/Sakura.tsx")
};
